CREATE TABLE Pit_Scouting_2017
(
	robot_key	CHAR(20)	NOT NULL PRIMARY KEY,
	team_key	CHAR(10)	REFERENCES Teams(team_key),
	drive_train	CHAR(100)	,
	cims_used	INTEGER		,
	speed_fps	INTEGER		,
	speed_scaled	INTEGER	,
	shift_gears	BIT			,
	robot_wt	INTEGER		,
	ball_cap	INTEGER		,
	vision		BIT			,
	active_gear	BIT			,
	ground_gear	BIT			,
	run_sec		INTEGER		,
	run_scale	INTEGER		,
	ground_ball	BIT			,
	strategy	INTEGER		,
	start_pos	CHAR(10)	,
	baseline	BIT			,
	auto_gear	BIT			,
	auto_ball	INTEGER		,
	auto_low	BIT			,
	tele_gears	INTEGER		,
	tele_balls	INTEGER		,
	tele_low	BIT			,
	acc_scale	INTEGER		,
	climb		BIT			,
	climb_time	INTEGER		,
	comments	CHAR(1000)
)
